apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline
  labels:
    app: logstash
    chart: logstash-2.4.1
    heritage: Helm
data:
  logstash.conf: |-
    input {
      beats {
        port => 5044
      }
    }

    filter {
      json{
        source => "message"
        skip_on_invalid_json => true
      }

      mutate {
        remove_field => ["log", "cloud", "ecs", "agent", "input", "tags", "docker", "container", "host", "message", "@version"]
        remove_field => ["headers","host"]
      }
    }

    output {
      elasticsearch {
        hosts => ["elasticsearch-master:9200"]
        manage_template => false
        index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"
        user => "elastic"
        password => "gavradon"
      }
    }