name: Publish Release

on:
  push:
    branches-ignore:
      - 'master'
    tags-ignore:
      - v0.*

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.14.13' 
      - if: matrix.os == 'windows-latest'
        name: output
        run: $(shell pwd)
      - if: matrix.os == 'windows-latest'
        name: Install make in windows
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install make
      - name: Setup Go environment
        run: make install
      - if: matrix.os == 'windows-latest'
        name: Build go-spacemesh
        run: go build -ldflags “-X main.version=1.0 -X main.commit=5f1237a7ee06884d55712faf04655b064fe49225 -X main.branch=HEAD” -o ./build/go-spacemesh.exe
      - if: matrix.os == 'windows-latest'
        name: See build directory content
        run: dir ./build
      