name: Publish Release

on:
  push:
    branches-ignore:
      - 'master'
    tags-ignore:
      - v0.*

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.14.13' 
      - name: Set env vars
        env:
          GOPATH: ${{ github.workspace }}
          GO111MODULE: off
        defaults:
          run:
            working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
      - if: matrix.os == 'windows-latest'
        name: Install make in windows
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install make
      - name: Setup Go environment
        run: make install
      - name: Build go-spacemesh
        run: make build
      - if: matrix.os == 'windows-latest'
        name: See build directory content
        run: dir .
      - if: matrix.os == 'windows-latest'
        name: See go path
        run: echo %PATH%