name: Publish Release

# on:
#   push:
#     branches:
#       - master
#   workflow_dispatch:

on:
  push:
    branches-ignore:
      - 'master'
    tags-ignore:
      - v0.*

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.14.13' 
      - if: matrix.os == 'windows-latest'
        name: Install make in windows
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install make
      - if: matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest'
        name: Setup Go environment
        run: make install
      - name: Build go-spacemesh
        run: make build